@extends("layouts.Telun")
@section("link","{{ asset('../../css/home.css')}} ")
@section("pageTitle","home")
@section("title","home")
@section("content")
@foreach ($volunteer as $volunteer)
<h4>{{$volunteer['title']}}</h4>
<ul>
    <li>
        {{$volunteer['title']}}
    </li>
    <li>
        {{$volunteer['Recperi']}}
    </li>
    <li>
        {{$volunteer['holdperi']}}
    </li>
    <li>
        {{$volunteer['holdperi']}}
    </li>
    <li>
        {{$volunteer['price']}}
    </li>
    <li>
        {{$volunteer['pridesc']}}
    </li>
    <li>
        {{$volunteer['capa']}}
    </li>
    <li>
        {{$volunteer['price']}}
    </li>
        {{$volunteer['target']}}
        {{$volunteer['add']}}
        {{$volunteer['adddesc']}}
        {{$volunteer['station']}}
        {{$volunteer['comment']}}
        {{$volunteer['price']}}
        {{$volunteer['pridesc']}}
        {{$volunteer['capa']}}
        {{$volunteer['target']}}
        {{$volunteer['add']}}
        {{$volunteer['adddesc']}}
        {{$volunteer['station']}}
        {{$volunteer['comment']}}

</ul>
@endforeach
@endsection
